---
- include_tasks: redhat/install.yml
  when: ansible_os_family == "RedHat"

- include_tasks: archlinux/install.yml
  when: ansible_os_family == "Archlinux"

- name: install additional rubygems
  gem:
    name: "{{ item }}"
    user_install: yes
  with_items:
    - "{{ rubygems }}"
